import type { EnvEnvSchema } from "@saflib/env/env";
import type { ExpressEnvSchema } from "@saflib/express/env";
import type { NodeEnvSchema } from "@saflib/node/env";

/**
 * Environment variables for the `@saflib/ory-kratos-http` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface OryKratosEnvSchema
  extends EnvEnvSchema, ExpressEnvSchema, NodeEnvSchema {
  /**
   * Host URL for the Ory Kratos courier callback server (e.g. recipes-monolith:3000).
   */
  KRATOS_HANDLER_HTTP_HOST: string;
  /**
   * Base URL for the Ory Kratos admin API (e.g. http://kratos:4434). Used for server-side identity lookups.
   */
  KRATOS_ADMIN_API_URL?: string;
}

/**
 * `process.env` casted to the `OryKratosEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as OryKratosEnvSchema;
