# Add static client build steps here:
FROM saflib-templates-root:latest AS saflib-templates-root-builder
RUN npm run build

# BEGIN WORKFLOW AREA build-product-dependencies FOR product/init
FROM saflib-templates-clients:latest AS templates-builder

COPY ./deploy/env.templates.prod-local /app/env.templates.prod-local
RUN export $(grep -v "^#" /app/env.templates.prod-local | xargs) && DOMAIN=${DOMAIN} CLIENT_SUBDOMAINS=${CLIENT_SUBDOMAINS} SERVICE_SUBDOMAINS=${SERVICE_SUBDOMAINS} npm run build

# END WORKFLOW AREA

FROM caddy:2.11.3-builder-alpine AS caddy-rebuild
RUN xcaddy build v2.11.3

FROM caddy:2.11.3-alpine
COPY --from=caddy-rebuild /usr/bin/caddy /usr/bin/caddy
RUN apk upgrade --no-cache && rm -rf /var/cache/apk/*

# Copy over static client builds here:
COPY --from=saflib-templates-root-builder /app/templates/clients/root/.vitepress/dist /srv/templates-root

# BEGIN WORKFLOW AREA copy-product-assets FOR product/init
COPY --from=templates-builder /app/templates/clients/build/dist /srv/templates-clients
# END WORKFLOW AREA

COPY ./deploy/caddy/Caddyfile ./deploy/caddy/common.Caddyfile ./deploy/caddy/templates.Caddyfile /etc/caddy/
COPY ./deploy/caddy/env.defaults /etc/templates/env.defaults
COPY ./deploy/scripts/apply-env-defaults.sh /usr/local/bin/apply-env-defaults.sh
RUN chmod +x /usr/local/bin/apply-env-defaults.sh

ENTRYPOINT ["/usr/local/bin/apply-env-defaults.sh", "caddy"]
CMD ["run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
