import type { EnvEnvSchema } from "@saflib/env/env";
import type { NodeEnvSchema } from "@saflib/node/env";

/**
 * Environment variables for the `@saflib/express` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface ExpressEnvSchema extends EnvEnvSchema, NodeEnvSchema {
  /**
   * When 'true', skip MFA gates on admin routes and operations tagged mfa-required. Useful for local development.
   */
  DISABLE_MFA_ENFORCEMENT?: "true" | "false";
}

/**
 * `process.env` casted to the `ExpressEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as ExpressEnvSchema;
