import { execFileSync } from "node:child_process";
import { writeFileSync, chmodSync } from "node:fs";
import path from "node:path";
import { resolveDevLayout } from "./layout.ts";

function gitConfig(key: string): string {
  try {
    return execFileSync("git", ["config", "--get", key], {
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

/** Writes `dev-site.env` beside the product dev compose files. */
export function writeDevSiteEnv(devDir: string): void {
  const layout = resolveDevLayout(devDir);
  const outPath = path.join(layout.devDir, "dev-site.env");

  const gitAuthorName = gitConfig("user.name");
  const gitAuthorEmail = gitConfig("user.email");

  const lines = [
    "# Generated by saf-dev-site prepare — do not commit",
    `DEV_SITE_REPO_MOUNT=${layout.repoMount}`,
    `DEV_SITE_PRODUCT_ROOT=${layout.productRoot}`,
    `DEV_SITE_SAFLIB_ROOT=${layout.containerSaflibRoot}`,
    `GIT_AUTHOR_NAME=${gitAuthorName}`,
    `GIT_AUTHOR_EMAIL=${gitAuthorEmail}`,
    `GIT_COMMITTER_NAME=${gitAuthorName}`,
    `GIT_COMMITTER_EMAIL=${gitAuthorEmail}`,
  ];

  if (layout.gitDirMount) {
    lines.push(`DEV_SITE_GIT_DIR_MOUNT=${layout.gitDirMount}`);
    console.error(
      `dev-site: repo=${layout.repoMount} product=${layout.productRoot} git-dir=${layout.gitDirMount}`,
    );
  } else {
    console.error(
      `dev-site: repo=${layout.repoMount} product=${layout.productRoot}`,
    );
  }

  writeFileSync(outPath, `${lines.join("\n")}\n`);
  chmodSync(outPath, 0o600);
}
