import type { NodeEnvSchema } from "@saflib/node/env";

/**
 * Environment variables for the `@saflib/backup-service-common` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface BackupServiceCommonEnvSchema extends NodeEnvSchema {
  BACKUP_SERVICE_HTTP_PORT: string;
  BACKUP_SERVICE_HOST: string;
}

/**
 * `process.env` casted to the `BackupServiceCommonEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as BackupServiceCommonEnvSchema;
