import type { EnvEnvSchema } from "@saflib/env/env";
import type { NodeEnvSchema } from "@saflib/node/env";

/**
 * Environment variables for the `@saflib/drizzle` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface DrizzleEnvSchema extends EnvEnvSchema, NodeEnvSchema {
  /**
   * Whether to allow the creation of new databases. Useful for ensuring existing production environments don't inadvertently create new databases.
   */
  ALLOW_DB_CREATION?: "true" | "false";
}

/**
 * `process.env` casted to the `DrizzleEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as DrizzleEnvSchema;
