# syntax=docker/dockerfile:labs
FROM node:24-slim AS builder

RUN npm install -g npm@11.14.1

WORKDIR /app
#{ copy_packages }#
RUN npm ci --omit=dev
#{ copy_src }#

WORKDIR /app/templates/clients/root
