import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/vendors-sentry` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface VendorsSentryEnvSchema extends EnvEnvSchema {
  SENTRY_DSN?: string;
  SENTRY_AUTH_TOKEN?: string;
}

/**
 * `process.env` casted to the `VendorsSentryEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as VendorsSentryEnvSchema;
