import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/analytics-service` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface AnalyticsServiceEnvSchema extends EnvEnvSchema {
  /**
   * PostHog project API key for server-side capture. Omit, leave empty, or set to "mock" to use the in-memory analytics implementation (no network).
   */
  POSTHOG_PROJECT_API_KEY?: string;
  /**
   * PostHog ingest host for server-side capture. Defaults to https://us.i.posthog.com when unset.
   */
  POSTHOG_PROJECT_HOST?: string;
}

/**
 * `process.env` casted to the `AnalyticsServiceEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as AnalyticsServiceEnvSchema;
