# syntax=docker/dockerfile:labs
FROM node:alpine3.19

# install saflib
WORKDIR /app
COPY tsconfig.json ./

#{ copy_packages }#
RUN npm install --omit=dev

#{ copy_src }#

WORKDIR /app/saflib/auth-service
CMD ["npm", "start"]