openapi: 3.0.0
info:
  title: base API
  version: 1.0.0
  description: API specification for the base service

paths:
  /jobs-demo/start:
    post:
      $ref: "./routes/jobs-demo/start.yaml#/startJobsDemo"
  /jobs-demo/step-b:
    post:
      $ref: "./routes/jobs-demo/step-b.yaml#/jobsDemoStepB"
  /jobs-demo/step-c:
    post:
      $ref: "./routes/jobs-demo/step-c.yaml#/jobsDemoStepC"
  /user-configs/mine:
    get:
      $ref: "./routes/user-configs/get-mine.yaml#/getMineUserConfigs"
    put:
      $ref: "./routes/user-configs/put-mine.yaml#/putMineUserConfigs"
  /user-configs/unsubscribe-marketing:
    post:
      $ref: "./routes/user-configs/unsubscribe-marketing.yaml#/unsubscribeMarketingEmailsUserConfigs"
  /admin/users/by-id:
    get:
      $ref: "./routes/admin/users-by-id.yaml#/getUsersByIdAdmin"
  # BEGIN WORKFLOW AREA route-paths FOR openapi/route
  __url-path__:
    __method__:
      $ref: "./routes/__group-name__/__target-name__.yaml#/__operationId__"
  # END WORKFLOW AREA

  # BEGIN WORKFLOW AREA offshoot-paths FOR openapi/init
  /__offshoot-name__/health:
    get:
      $ref: "../../__offshoot-name__/spec/routes/health.yaml#/get__OffshootName__Health"
  # END WORKFLOW AREA

components:
  schemas:
    Error:
      $ref: "pkg:@saflib/openapi/schemas/error.yaml"
    ProductEvent:
      $ref: "./events/index.yaml"
    UserConfig:
      $ref: "./schemas/user-config.yaml"
    KratosIdentity:
      $ref: "./schemas/kratos-identity.yaml"
    # BEGIN WORKFLOW AREA schema-components FOR openapi/schema
    __TargetName__:
      $ref: "./schemas/__target-name__.yaml"
    # END WORKFLOW AREA
