import { describe, it, expect, beforeAll, afterAll, beforeEach } from "vitest";
import { mkdtempSync, readFileSync, cpSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import type { DbKey } from "@saflib/new-workflows-db";
import { newWorkflowsDbManager } from "@saflib/new-workflows-db/instances";
import { createRun, advanceRun, collectOutput } from "@saflib/new-workflows";
import { templatesProductRoot } from "@saflib/templates";
import { AddEventWorkflowDefinition } from "./add-event.ts";

describe("openapi/add-event (ported to the new engine)", () => {
  let dbKey: DbKey;

  beforeAll(() => {
    dbKey = newWorkflowsDbManager.connect();
  });

  afterAll(() => {
    newWorkflowsDbManager.disconnect(dbKey);
  });

  beforeEach(() => {
    newWorkflowsDbManager.clearAllTablesForTests(dbKey);
  });

  it("copies the event template into the events dir with snake_case naming", async () => {
    const cwd = mkdtempSync(path.join(tmpdir(), "openapi-add-event-"));
    // `dist/openapi.d.ts`/`dist/openapi.json` are pre-generated build output
    // bundled in the golden template, not workflow-area-marked files — they
    // still contain OTHER workflows' unresolved `__placeholder__` tokens
    // (e.g. `openapi/route`'s `__url-path__`) until a real product's own
    // `saf-specs generate` overwrites them. A real product checkout already
    // has these files (generated by product/init), so the copy step upserts
    // into them rather than freshly instantiating the raw stub — seed the
    // same real spec package here so this test hits that same path.
    cpSync(path.join(templatesProductRoot, "service", "spec"), cwd, { recursive: true });

    const runId = await createRun(dbKey, AddEventWorkflowDefinition, {
      input: { path: "./events/product-view.yaml" },
      cwd,
      mode: "script",
    });

    const { output, result } = advanceRun(dbKey, AddEventWorkflowDefinition, runId);
    await collectOutput(output);
    const outcome = await result;
    expect(outcome.status).toBe("success");

    const eventPath = path.join(cwd, "events", "product_view.yaml");
    expect(readFileSync(eventPath, "utf-8")).toContain("product_view");
  });

  it("threads a passed prompt into the update step's prompt text", () => {
    const cwd = mkdtempSync(path.join(tmpdir(), "openapi-add-event-"));
    const context = AddEventWorkflowDefinition.context({
      input: { path: "./events/product-view.yaml", prompt: "user views a product detail page" },
      cwd,
    });
    const updateStep = AddEventWorkflowDefinition.steps[1];
    const stepInput = updateStep.input({ context }) as { prompt: string };
    expect(stepInput.prompt).toContain("Task: user views a product detail page");
  });
});
