/**
 * SVG paths for `mdi-*` strings used by dev-site UI.
 * Webfont CSS is unreliable in SPAs; use the SVG iconset instead.
 */
import {
  mdiApi,
  mdiCheck,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronRight,
  mdiChevronTripleRight,
  mdiCircleSmall,
  mdiClose,
  mdiCloseCircle,
  mdiCog,
  mdiConnection,
  mdiCube,
  mdiCubeOutline,
  mdiDatabaseOutline,
  mdiFastForward,
  mdiFileDocumentOutline,
  mdiFileOutline,
  mdiFolderOutline,
  mdiHistory,
  mdiHome,
  mdiLibraryShelves,
  mdiPackageVariantClosed,
  mdiPauseCircle,
  mdiPlay,
  mdiPlayCircleOutline,
  mdiProgressClock,
  mdiRepeat,
  mdiRewind,
  mdiStop,
  mdiTable,
  mdiTestTube,
  mdiVolumeHigh,
  mdiVolumeMedium,
  mdiVolumeOff,
  mdiVuejs,
} from "@mdi/js";

export const mdiIconPaths: Record<string, string> = {
  "mdi-api": mdiApi,
  "mdi-check": mdiCheck,
  "mdi-check-circle": mdiCheckCircle,
  "mdi-chevron-down": mdiChevronDown,
  "mdi-chevron-right": mdiChevronRight,
  "mdi-chevron-triple-right": mdiChevronTripleRight,
  "mdi-circle-small": mdiCircleSmall,
  "mdi-close": mdiClose,
  "mdi-close-circle": mdiCloseCircle,
  "mdi-cog": mdiCog,
  "mdi-connection": mdiConnection,
  "mdi-cube": mdiCube,
  "mdi-cube-outline": mdiCubeOutline,
  "mdi-database-outline": mdiDatabaseOutline,
  "mdi-fast-forward": mdiFastForward,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-file-outline": mdiFileOutline,
  "mdi-folder-outline": mdiFolderOutline,
  "mdi-history": mdiHistory,
  "mdi-home": mdiHome,
  "mdi-library-shelves": mdiLibraryShelves,
  "mdi-package-variant-closed": mdiPackageVariantClosed,
  "mdi-pause-circle": mdiPauseCircle,
  "mdi-play": mdiPlay,
  "mdi-play-circle-outline": mdiPlayCircleOutline,
  "mdi-progress-clock": mdiProgressClock,
  "mdi-repeat": mdiRepeat,
  "mdi-rewind": mdiRewind,
  "mdi-stop": mdiStop,
  "mdi-table": mdiTable,
  "mdi-test-tube": mdiTestTube,
  "mdi-volume-high": mdiVolumeHigh,
  "mdi-volume-medium": mdiVolumeMedium,
  "mdi-volume-off": mdiVolumeOff,
  "mdi-vuejs": mdiVuejs,
};
