# syntax=docker/dockerfile:labs
FROM node:alpine3.19

WORKDIR /app

#{ copy_packages }#
RUN npm ci --omit=dev
#{ copy_src }#

WORKDIR /app/__product-name__/service/monolith

COPY ./deploy/__product-name__/env.defaults /etc/__product-name__/env.defaults
COPY ./deploy/scripts/apply-env-defaults.sh /usr/local/bin/apply-env-defaults.sh
RUN chmod +x /usr/local/bin/apply-env-defaults.sh

ENTRYPOINT ["/usr/local/bin/apply-env-defaults.sh"]
CMD ["npm", "start"]

