# syntax=docker/dockerfile:labs
FROM node:alpine3.19

WORKDIR /app

#{ copy_packages }#
RUN npm install --omit=dev
#{ copy_src }#

WORKDIR /app/services/template-file/template-file-service
CMD ["npm", "start"]
