import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/vendors-infisical` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface VendorsInfisicalEnvSchema extends EnvEnvSchema {
  /**
   * Infisical access token for the secret store. Sentinel "mock" selects the mock Infisical client (returns env fallbacks / placeholders).
   */
  INFISICAL_TOKEN: string;
  /**
   * Infisical project id. Optional when INFISICAL_TOKEN is "mock".
   */
  INFISICAL_PROJECT_ID?: string;
  /**
   * Infisical environment slug (e.g. dev, staging, prod). Optional when INFISICAL_TOKEN is "mock".
   */
  INFISICAL_ENVIRONMENT?: string;
}

/**
 * `process.env` casted to the `VendorsInfisicalEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as VendorsInfisicalEnvSchema;
