/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CombinedEnvSchema {
  /**
   * Comma-separated list of client subdomains, e.g. 'www,app,auth,'. Include an empty string (such as in the example) to indicate there's a client for the root domain.
   */
  CLIENT_SUBDOMAINS: string;
  /**
   * The name of the deployment, e.g. 'production', 'staging', 'development'. This may be used in strings such as database file names and logging metadata; each deployment should have a unique name.
   */
  DEPLOYMENT_NAME: string;
  /**
   * The root domain of the deployment, e.g. 'saf.com'.
   */
  DOMAIN: string;
  /**
   * The protocol of the deployment, e.g. 'https'
   */
  PROTOCOL: "https" | "http";
  /**
   * The timezone of the deployment, e.g. 'America/New_York'. Must be UTC.
   */
  TZ: "UTC";
  /**
   * The environment of the deployment. Generally should avoid using this, consider its use deprecated, prefer instead more specific environment variables.
   */
  NODE_ENV: "development" | "production" | "test";
  /**
   * Whether to mock 3rd party integrations. Set to 'true' to mock. And integration packages should respect this setting.
   */
  MOCK_INTEGRATIONS?: "true" | "false";
  /**
   * Whether to allow the creation of new databases. Useful for ensuring existing production environments don't inadvertently create new databases.
   */
  ALLOW_DB_CREATION?: "true" | "false";
}

let typedEnv: CombinedEnvSchema;
if (globalThis.process) {
  typedEnv = process.env as unknown as CombinedEnvSchema;
} else {
  typedEnv = {} as CombinedEnvSchema;
}
export { typedEnv };
