name: Typecheck

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-deps
      - name: Run Typecheck
        run: npm run typecheck
