name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          # BEGIN WORKFLOW AREA test-product-dependencies FOR product/init
          - base
          # END WORKFLOW AREA
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-deps

      - name: Run Unit Tests
        run: npm run test -- --project='*${{ matrix.project }}*'
