name: Unit Tests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          # BEGIN WORKFLOW AREA test-product-dependencies FOR product/init
          - base
          # END WORKFLOW AREA
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-node-deps

      - name: Run Unit Tests
        run: npm run test -- --project='*${{ matrix.project }}*'
