import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/vendors-azure` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface VendorsAzureEnvSchema extends EnvEnvSchema {
  /**
   * Azure Blob Storage account URL for the Hot access tier.
   */
  AZURE_HOT_BLOB_STORAGE_URL?: string;
  /**
   * Azure Blob Storage account URL for the Cool access tier.
   */
  AZURE_COOL_BLOB_STORAGE_URL?: string;
  /**
   * Azure Blob Storage account URL for the Cold access tier.
   */
  AZURE_COLD_BLOB_STORAGE_URL?: string;
}

/**
 * `process.env` casted to the `VendorsAzureEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as VendorsAzureEnvSchema;
