# Add static client build steps here:
FROM saflib-tmp-root:latest AS saflib-tmp-root-builder
RUN npm run build

# BEGIN WORKFLOW AREA build-product-dependencies FOR product/init
FROM saflib-tmp-clients:latest AS tmp-builder

COPY ./deploy/env.tmp.prod-local /app/env.tmp.prod-local
RUN export $(grep -v "^#" /app/env.tmp.prod-local | xargs) && DOMAIN=${DOMAIN} CLIENT_SUBDOMAINS=${CLIENT_SUBDOMAINS} SERVICE_SUBDOMAINS=${SERVICE_SUBDOMAINS} npm run build

# END WORKFLOW AREA

FROM caddy:2.11.3-builder-alpine AS caddy-rebuild
RUN xcaddy build v2.11.3

FROM caddy:2.11.3-alpine
COPY --from=caddy-rebuild /usr/bin/caddy /usr/bin/caddy
RUN apk upgrade --no-cache && rm -rf /var/cache/apk/*

# Copy over static client builds here:
COPY --from=saflib-tmp-root-builder /app/tmp/clients/root/.vitepress/dist /srv/tmp-root

# BEGIN WORKFLOW AREA copy-product-assets FOR product/init
COPY --from=tmp-builder /app/tmp/clients/build/dist /srv/tmp-clients
# END WORKFLOW AREA

COPY ./deploy/remote-assets/config /etc/caddy/
