services:
  caddy:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: caddy
    volumes: !override []
    env_file: !override
      - ./env.caddy.prod-local

  # BEGIN WORKFLOW AREA monolith FOR product/init
  __product-name__-monolith:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: __product-name__-monolith
    volumes: !override []
    env_file: !override
      - ./env.__product-name__.prod-local
  
  # END WORKFLOW AREA

  loki:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: loki
    volumes:
      - ./remote-assets/loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  prometheus:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: prometheus
    volumes:
      - ./remote-assets/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: grafana
    volumes: !override []


  kratos-migrate:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: kratos-migrate
    volumes: !override
      - ./kratos-prod-local/data:/var/lib/sqlite
      - ./kratos-prod-local:/etc/config/kratos

  kratos:
    extends:
      file: remote-assets/docker-compose.prod.yaml
      service: kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    env_file: !override
      - ./env.kratos.config.prod-local
      - ./env.kratos.prod-local
    volumes: !override
      - ./kratos-prod-local/data:/var/lib/sqlite
      - ./kratos-prod-local:/etc/config/kratos
      
volumes:
  caddy_data:
  caddy_config:
