# common elements between dev and test
services:
  clients:
    ports:
      - 5173:5173
    build:
      context: __reverse-path__
      dockerfile: ./__rel-dir__/Dockerfile
    command: npm run dev
    volumes:
      - ./:/app/__rel-dir__/
      - __reverse-path__/saflib/vue/:/app/saflib/vue/
      - __reverse-path__/saflib/sdk/:/app/saflib/sdk/
