# syntax=docker/dockerfile:labs
FROM node:24-slim AS builder

RUN npm install -g npm@11.14.1

# Copy package.json
WORKDIR /app

#{ copy_packages }#
RUN npm ci

#{ copy_src }#

# Vue app setup
WORKDIR /app/__rel-dir__