# syntax=docker/dockerfile:labs
FROM node:alpine

# install saflib
WORKDIR /app
COPY tsconfig.json ./

#{ copy_packages }#
RUN npm install --omit=dev

#{ copy_src }#

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["npm", "run", "healthcheck"]
WORKDIR /app/saflib/auth-service
CMD ["npm", "start"]