import type { BaseServiceCommonEnvSchema } from "@saflib/base-service-common/env";
import type { EnvEnvSchema } from "@saflib/env/env";
import type { ExpressEnvSchema } from "@saflib/express/env";
import type { NodeEnvSchema } from "@saflib/node/env";
import type { VendorsLokiEnvSchema } from "@saflib/vendors-loki/env";
import type { VendorsSentryEnvSchema } from "@saflib/vendors-sentry/env";

/**
 * Environment variables for the `@saflib/base-monolith` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface BaseMonolithEnvSchema extends BaseServiceCommonEnvSchema, EnvEnvSchema, ExpressEnvSchema, NodeEnvSchema, VendorsLokiEnvSchema, VendorsSentryEnvSchema {}

/**
 * `process.env` casted to the `BaseMonolithEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as BaseMonolithEnvSchema;
