import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/vendors-posthog-client` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface VendorsPosthogClientEnvSchema extends EnvEnvSchema {
  POSTHOG_PROJECT_API_KEY: string;
  POSTHOG_PROJECT_HOST: string;
}

/**
 * `process.env` casted to the `VendorsPosthogClientEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as VendorsPosthogClientEnvSchema;
