# syntax=docker/dockerfile:labs
FROM node:22-slim AS builder

# Copy package.json
WORKDIR /app

#{ copy_packages }#
RUN npm install --omit=dev
# RUN npm install @rollup/rollup-linux-arm64-gnu

#{ copy_src }#

# Vue app setup
WORKDIR /app/clients/__product-name__/__product-name__-clients