import type { EnvEnvSchema } from "@saflib/env/env";
import type { TemplatePackageGrpcProtoEnvSchema } from "template-package-grpc-proto/env";

/**
 * Environment variables for the `template-package-grpc-client` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface TemplatePackageGrpcClientEnvSchema
  extends EnvEnvSchema, TemplatePackageGrpcProtoEnvSchema {}

/**
 * `process.env` casted to the `TemplatePackageGrpcClientEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as TemplatePackageGrpcClientEnvSchema;
