import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/vendors-loki` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface VendorsLokiEnvSchema extends EnvEnvSchema {
  /**
   * The hostname or URL of the Loki instance to send logs to (e.g., http://loki:3100)
   */
  LOKI_HOSTNAME?: string;
  /**
   * The port number of the Loki instance to send logs to (e.g., 3100)
   */
  LOKI_PORT?: string;
}

/**
 * `process.env` casted to the `VendorsLokiEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as VendorsLokiEnvSchema;
