#!/usr/bin/env bash
# Writes dev-site.env with repo mount + product root for the current checkout layout.
#
# Canonical product scope is always base/ within the saflib repo (matches a copied product).
# When saflib is a pathclerk submodule, also mount the submodule git dir so git plumbing works.
set -euo pipefail

DEV_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SAFLIB_ROOT="$(cd "$DEV_DIR/../.." && pwd)"
OUT="$DEV_DIR/dev-site.env"

PRODUCT_ROOT="base"
REPO_MOUNT="$SAFLIB_ROOT"

cat > "$OUT" <<EOF
# Generated by scripts/resolve-dev-site-env.sh — do not commit
DEV_SITE_REPO_MOUNT=$REPO_MOUNT
DEV_SITE_PRODUCT_ROOT=$PRODUCT_ROOT
EOF

if [[ -f "$SAFLIB_ROOT/.git" ]] && grep -q '^gitdir:' "$SAFLIB_ROOT/.git" 2>/dev/null; then
  GIT_DIR_MOUNT="$(cd "$SAFLIB_ROOT/.." && pwd)/.git/modules/saflib"
  if [[ -d "$GIT_DIR_MOUNT" ]]; then
    cat >> "$OUT" <<EOF
DEV_SITE_GIT_DIR_MOUNT=$GIT_DIR_MOUNT
EOF
    echo "dev-site: repo=$REPO_MOUNT (saflib submodule) product=$PRODUCT_ROOT git-dir=$GIT_DIR_MOUNT" >&2
  else
    echo "dev-site: repo=$REPO_MOUNT product=$PRODUCT_ROOT (submodule git dir missing at $GIT_DIR_MOUNT)" >&2
  fi
else
  echo "dev-site: repo=$REPO_MOUNT product=$PRODUCT_ROOT" >&2
fi
