#!/usr/bin/env bash
# Writes dev-site.env with repo mount + product root for the current checkout layout.
#
# Canonical product scope is always base/ within the saflib repo (matches a copied product).
# When saflib is a git submodule of a parent monorepo, also mount the submodule git dir so git plumbing works.
set -euo pipefail

DEV_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SAFLIB_ROOT="$(cd "$DEV_DIR/../.." && pwd)"
OUT="$DEV_DIR/dev-site.env"

PRODUCT_ROOT="base"
REPO_MOUNT="$SAFLIB_ROOT"

# Workflow "update"/step commits (see @saflib/new-workflows's `commitIfDirty`)
# run as the container's `node` user, which has no git identity of its own —
# `git commit` fails outright ("unable to auto-detect email address") without
# this. Forwarded as GIT_AUTHOR_*/GIT_COMMITTER_* env vars (which git reads
# directly, no `git config --global` needed) rather than bind-mounting the
# host's ~/.gitconfig, since a template global config can carry unrelated
# host-specific settings (signing keys, includeIf blocks) that don't
# translate into the container. Empty string if the host has no identity
# configured either — same "soft failure, still proceed" approach as
# resolve-claude-credentials.sh; a workflow needing to commit just fails
# with the same clear error until the host sets one.
GIT_AUTHOR_NAME="$(git config --get user.name || true)"
GIT_AUTHOR_EMAIL="$(git config --get user.email || true)"

# Where @saflib/templates should resolve its root from *inside the
# container*, not from wherever the code happens to be loaded from (see
# saflib/templates/index.ts's SAFLIB_ROOT override) — self-determining so
# this works whichever layout the repo mount turns out to be: saflib as
# the repo root itself, or nested as a submodule under it.
if [[ -d "$REPO_MOUNT/saflib" ]]; then
  CONTAINER_SAFLIB_ROOT="/repo/saflib"
else
  CONTAINER_SAFLIB_ROOT="/repo"
fi

cat > "$OUT" <<EOF
# Generated by scripts/resolve-dev-site-env.sh — do not commit
DEV_SITE_REPO_MOUNT=$REPO_MOUNT
DEV_SITE_PRODUCT_ROOT=$PRODUCT_ROOT
DEV_SITE_SAFLIB_ROOT=$CONTAINER_SAFLIB_ROOT
GIT_AUTHOR_NAME=$GIT_AUTHOR_NAME
GIT_AUTHOR_EMAIL=$GIT_AUTHOR_EMAIL
GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
EOF

if [[ -f "$SAFLIB_ROOT/.git" ]] && grep -q '^gitdir:' "$SAFLIB_ROOT/.git" 2>/dev/null; then
  GIT_DIR_MOUNT="$(cd "$SAFLIB_ROOT/.." && pwd)/.git/modules/saflib"
  if [[ -d "$GIT_DIR_MOUNT" ]]; then
    cat >> "$OUT" <<EOF
DEV_SITE_GIT_DIR_MOUNT=$GIT_DIR_MOUNT
EOF
    echo "dev-site: repo=$REPO_MOUNT (saflib submodule) product=$PRODUCT_ROOT git-dir=$GIT_DIR_MOUNT" >&2
  else
    echo "dev-site: repo=$REPO_MOUNT product=$PRODUCT_ROOT (submodule git dir missing at $GIT_DIR_MOUNT)" >&2
  fi
else
  echo "dev-site: repo=$REPO_MOUNT product=$PRODUCT_ROOT" >&2
fi
