import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/node` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface NodeEnvSchema extends EnvEnvSchema {
  /**
   * Minimum Winston log level for console output (error, warn, info, verbose, debug, silly). HTTP access lines via Morgan are unaffected.
   */
  LOG_LEVEL?: "error" | "warn" | "info" | "verbose" | "debug" | "silly";
  /**
   * Comma-separated list of emails who will get the 'admin' scope. Emails must be validated to receive this scope.
   */
  ADMIN_EMAILS: string;
  /**
   * HMAC keys for signing/verifying internal identity assertions. Format: keyId:base64secret[,keyId:base64secret]. Sign with the first entry; verify against all (rotation = prepend a new key). Sentinel `mock` (e.g. Infisical mock placeholder) expands to a fixed local key. Optional — only required in environments that use the internal request channel.
   */
  SAF_INTERNAL_ASSERTION_KEYS?: string;
}

/**
 * `process.env` casted to the `NodeEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as NodeEnvSchema;
