import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

export interface GitHashes {
  root: string;
  saflib: string;
}

const defaultHashes: GitHashes = { root: "unknown", saflib: "unknown" };

let cached: GitHashes | undefined;

/**
 * Reads git hashes from the JSON file generated by `saf-git-hashes`.
 * Falls back to `{ root: "unknown", saflib: "unknown" }` when the file
 * is missing (e.g. local dev without running the generator).
 */
export function getGitHashes(): GitHashes {
  if (cached) return cached;
  try {
    const dir = dirname(fileURLToPath(import.meta.url));
    const raw = readFileSync(join(dir, "..", "git-hashes.json"), "utf8");
    const data = JSON.parse(raw) as Partial<GitHashes>;
    cached = {
      root: data.root ?? "unknown",
      saflib: data.saflib ?? "unknown",
    };
  } catch {
    cached = defaultHashes;
  }
  return cached;
}
