# syntax=docker/dockerfile:labs
FROM node:22-slim AS builder

# Copy package.json
WORKDIR /app

#{ copy_packages }#
RUN npm install
RUN npm install @rollup/rollup-linux-arm64-gnu

#{ copy_src }#

# Vue app setup
WORKDIR /app/secrets/secrets-sdk