/**
 * This file was automatically generated by @saflib/env.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run "npm exec saf-env generate" to regenerate this file.
 */

export interface CombinedEnvSchema {
  IDENTITY_SERVICE_HTTP_PORT: string;
  IDENTITY_SERVICE_GRPC_PORT: string;
}

export const typedEnv = (globalThis.process ? process.env : {}) as unknown as CombinedEnvSchema;
