# syntax=docker/dockerfile:labs
FROM node:alpine3.19

WORKDIR /app

#{ copy_packages }#
RUN --mount=type=cache,target=/root/.npm npm ci --omit=dev
#{ copy_src }#

WORKDIR /app/services/cron
CMD ["npm", "start"]