import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/base-__integration-name__-integration` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface Base_IntegrationName__IntegrationEnvSchema {
  /**
   * The API key for the __INTEGRATION_NAME__ integration
   */
  __INTEGRATION_NAME___API_KEY?: string;
}

/**
 * `process.env` casted to the `Base__integrationName__IntegrationEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as Base__integrationName__IntegrationEnvSchema;
