import type { BaseServiceCommonEnvSchema } from "@saflib/base-service-common/env";
import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `template-package-grpc-proto` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface TemplatePackageGrpcProtoEnvSchema
  extends BaseServiceCommonEnvSchema, EnvEnvSchema {
  /**
   * The host on which the gRPC server will listen, or the client will connect.
   */
  __SERVICE_NAME___SERVICE_GRPC_HOST: string;
}

/**
 * `process.env` casted to the `TemplatePackageGrpcProtoEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as TemplatePackageGrpcProtoEnvSchema;
