import type { Base__integrationName__IntegrationEnvSchema } from "@saflib/base-__integration-name__-integration/env";
import type { DrizzleEnvSchema } from "@saflib/drizzle/env";
import type { NodeEnvSchema } from "@saflib/node/env";

/**
 * Environment variables for the `@saflib/base-service-common` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface BaseServiceCommonEnvSchema
  extends
    Base__integrationName__IntegrationEnvSchema,
    DrizzleEnvSchema,
    NodeEnvSchema {
  BASE_SERVICE_HTTP_HOST: string;
}

/**
 * `process.env` casted to the `BaseServiceCommonEnvSchema` type.
 */
export const typedEnv = (globalThis.process
  ? process.env
  : {}) as unknown as BaseServiceCommonEnvSchema;
