# syntax=docker/dockerfile:labs
FROM node:24-slim AS builder

WORKDIR /app
#{ copy_packages }#
RUN npm install --omit=dev
#{ copy_src }#

WORKDIR /app/__product-name__/clients/__static-subdomain-name__
