import type { EnvEnvSchema } from "@saflib/env/env";

/**
 * Environment variables for the `@saflib/vendors-sentry-node` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface VendorsSentryNodeEnvSchema extends EnvEnvSchema {
  SENTRY_DSN?: string;
  SENTRY_AUTH_TOKEN?: string;
}

/** @deprecated Use {@link VendorsSentryNodeEnvSchema}. */
export type VendorsSentryEnvSchema = VendorsSentryNodeEnvSchema;

/**
 * `process.env` casted to the `VendorsSentryNodeEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as VendorsSentryNodeEnvSchema;
