name: Workflows in Print Mode

on:
  pull_request:
    branches:
      - main

jobs:
  workflow-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      # Main test. Runs the basic tests in print mode, automatically getting the next prompt until done.
      - name: Run Workflow Integration Test
        run: ./test-all-steps-runner.ts
        working-directory: ./workflows-cli

      # just for debugging, checking all the files that got added/changed
      - name: Git status
        run: git status -uall
