import type { EnvEnvSchema } from "@saflib/env/env";
import type { ExpressEnvSchema } from "@saflib/express/env";
import type { NodeEnvSchema } from "@saflib/node/env";

/**
 * Environment variables for the `@saflib/base-dev-site-http` package, including inherited variables via `extends`.
 * Generated by `@saflib/env`. To update, make changes to the adjacent `env.schema.json`, navigate to the package root, and run `npm exec saf-env generate`.
 */
export interface BaseDevSiteHttpEnvSchema extends EnvEnvSchema, ExpressEnvSchema, NodeEnvSchema {
  /**
   * Host:port for the HTTP listener (e.g. 0.0.0.0:3099). Port is parsed from the value after the last colon.
   */
  DEV_SITE_SERVICE_HTTP_HOST?: string;
  /**
   * Absolute path to the git repository to analyze. Defaults to process.cwd() when unset.
   */
  DEV_SITE_REPO_ROOT?: string;
  /**
   * Path prefix within the repo to analyze (e.g. base). Empty string = whole repo.
   */
  DEV_SITE_PRODUCT_ROOT?: string;
  /**
   * Main branch ref used for history walks and is-main-ancestor checks.
   */
  DEV_SITE_MAIN_REF?: string;
  /**
   * Absolute path to the SQLite database file. Defaults to ./data/dev-site.sqlite beside this package.
   */
  DEV_SITE_DB_PATH?: string;
  /**
   * Optional absolute path to built SPA assets. When set, Express serves the UI and API on one port.
   */
  DEV_SITE_STATIC_DIR?: string;
}

/**
 * `process.env` casted to the `BaseDevSiteHttpEnvSchema` type.
 */
export const typedEnv = (globalThis.process ? process.env : {}) as unknown as BaseDevSiteHttpEnvSchema;
