import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { listIgnored, repoRootFor } from "@saflib/git";
import { parseContextSources } from "./inputs.ts";

/**
 * BuildKit's Dockerfile-specific ignore file: `<Dockerfile>.dockerignore`
 * next to the Dockerfile replaces the context's `.dockerignore` for that build.
 */
export function contextIgnorePath(dockerfilePath: string): string {
  return `${dockerfilePath}.dockerignore`;
}

const toPosix = (p: string) => p.split(path.sep).join("/");
/** Escapes `.dockerignore` (Go filepath.Match) metacharacters. */
const escapePattern = (p: string) => p.replace(/[*?[\]\\]/g, "\\$&");

/**
 * Context-relative paths of every gitignored file or directory under the
 * Dockerfile's `COPY`/`ADD` sources — local data, dev databases, logs and
 * other things that aren't part of the input hash and shouldn't ship.
 * Sources that are themselves gitignored (e.g. the staged install manifests)
 * are left alone. Empty when git isn't available.
 */
export function gitignoredContextPaths(
  contextDir: string,
  dockerfile: string,
): string[] {
  const byRepo = new Map<string, { source: string; repoRelative: string }[]>();
  for (const source of parseContextSources(dockerfile)) {
    const { result: repoRoot, error } = repoRootFor(
      path.join(contextDir, source),
    );
    if (error) continue;
    const repoRelative = toPosix(
      path.relative(repoRoot, path.join(contextDir, source)),
    );
    const group = byRepo.get(repoRoot) ?? [];
    group.push({ source, repoRelative });
    byRepo.set(repoRoot, group);
  }
  const paths = new Set<string>();
  for (const [repoRoot, group] of byRepo) {
    const { result: ignored, error } = listIgnored(
      repoRoot,
      group.map((g) => g.repoRelative),
    );
    if (error) continue;
    for (const entry of ignored) {
      const trimmed = entry.replace(/\/$/, "");
      // An entry covering a whole source means the source itself is ignored.
      const coversSource = group.some(
        (g) =>
          g.repoRelative === trimmed ||
          g.repoRelative.startsWith(`${trimmed}/`) ||
          trimmed === "",
      );
      if (coversSource) continue;
      paths.add(
        toPosix(path.relative(contextDir, path.join(repoRoot, trimmed))),
      );
    }
  }
  return [...paths].sort();
}

/**
 * Contents of a build's `<Dockerfile>.dockerignore`: the context's
 * `.dockerignore` rules plus every gitignored path under the build's sources,
 * so the build context holds exactly what git sees (and the input hash
 * covers).
 */
export function generateContextIgnore(
  contextDir: string,
  dockerfile: string,
): string {
  const rootFile = path.join(contextDir, ".dockerignore");
  const root = existsSync(rootFile)
    ? readFileSync(rootFile, "utf8").trimEnd()
    : "";
  const ignored = gitignoredContextPaths(contextDir, dockerfile);
  return [
    "# Generated by `saf-docker generate`; do not edit.",
    "# Context .dockerignore:",
    root,
    "",
    "# Gitignored paths under this build's COPY sources (local data, dev",
    "# databases, logs): not part of the input hash, so never shipped.",
    ...ignored.map(escapePattern),
    "",
  ].join("\n");
}
