import { parseInstructions } from "./inputs.ts";

/** Where build metadata lives inside images. */
export const BUILD_INFO_DIR = "/etc/saf";
/** This image's own build info. */
export const BUILD_INFO_FILE = `${BUILD_INFO_DIR}/build.json`;
/** Build info of this image and every upstream build it contains, by image. */
export const BUILD_INFOS_DIR = `${BUILD_INFO_DIR}/builds`;
/** Build arg carrying the JSON build info (see `saf-docker build`). */
export const BUILD_INFO_ARG = "SAF_BUILD_INFO";

/**
 * Written by `saf-docker build` into each image it builds. Only `commits` is
 * reported at runtime (see `@saflib/node` `getGitHashes`); the rest is for
 * diagnostics (`docker run … cat /etc/saf/build.json`).
 */
export interface BuildInfo {
  schema: 1;
  buildRef: string;
  image: string;
  inputHash: string;
  /** Commits the image was built from (`-dirty` if its inputs were). */
  commits: { root: string; saflib: string };
  dirty: boolean;
  platform: string;
  builtAt: string;
  /** Build refs of upstream builds this image consumes. */
  upstream: string[];
}

function stageName(args: string): { image: string; stage?: string } {
  const tokens = args.split(/\s+/).filter((t) => !t.startsWith("--"));
  const [image, as, stage] = tokens;
  return {
    image,
    stage: as?.toUpperCase() === "AS" ? stage?.toLowerCase() : undefined,
  };
}

/**
 * The generated final step of every Dockerfile: writes `SAF_BUILD_INFO` to
 * {@link BUILD_INFO_FILE} and {@link BUILD_INFOS_DIR}`/<image>.json`, after
 * copying the build infos of upstream build stages. It's the last layer, so
 * a changing build arg never invalidates earlier layers. The directory is
 * created even without the arg, so downstream builds can always copy it.
 *
 * `upstreamImages` are image names (no tag) of other builds; any stage built
 * `FROM` one of them, or `COPY --from` one directly, contributes its infos.
 */
export function buildMetadataStep(
  dockerfile: string,
  image: string,
  upstreamImages: ReadonlySet<string>,
): string {
  const instructions = parseInstructions(dockerfile);
  const isUpstream = (ref: string) =>
    upstreamImages.has(ref.split("@")[0].replace(/:[^/:]*$/, ""));

  let finalStageStart = -1;
  instructions.forEach((ins, i) => {
    if (ins.keyword === "FROM") finalStageStart = i;
  });

  const sources = new Set<string>();
  let finalUser: string | undefined;
  instructions.forEach((ins, i) => {
    if (ins.keyword === "FROM" && i !== finalStageStart) {
      const { image: from, stage } = stageName(ins.args);
      if (isUpstream(from)) sources.add(stage ?? from);
    }
    if (ins.keyword === "COPY" || ins.keyword === "ADD") {
      const from = ins.args
        .split(/\s+/)
        .find((t) => t.startsWith("--from="))
        ?.slice("--from=".length);
      if (from && isUpstream(from)) sources.add(from);
    }
    if (ins.keyword === "USER" && i > finalStageStart)
      finalUser = ins.args.trim();
  });

  const lines = [
    "",
    "# --- Build metadata (generated by saf-docker; keep last) ---",
  ];
  if (finalUser) lines.push("USER root");
  for (const source of sources) {
    lines.push(`COPY --from=${source} ${BUILD_INFOS_DIR}/ ${BUILD_INFOS_DIR}/`);
  }
  lines.push(
    `ARG ${BUILD_INFO_ARG}`,
    `RUN mkdir -p ${BUILD_INFOS_DIR} && if [ -n "$${BUILD_INFO_ARG}" ]; then printf '%s\\n' "$${BUILD_INFO_ARG}" > ${BUILD_INFO_FILE} && cp ${BUILD_INFO_FILE} ${BUILD_INFOS_DIR}/${image}.json; fi`,
  );
  if (finalUser) lines.push(`USER ${finalUser}`);
  return lines.join("\n") + "\n";
}
